<a href="https://colab.research.google.com/github/jinuElsa/Data-Science/blob/main/exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix operation

In [2]:
import numpy as np
m1=np.array([[1,3],[2,6]])
m2=np.array([[0,1],[1,9]])
print("Original 2-d matrix:")
print(m1)
print(m2)

print("Outer product of the two matrix is: ")
result=np.outer(m1,m2)
print(result)

Original 2-d matrix:
[[1 3]
 [2 6]]
[[0 1]
 [1 9]]
Outer product of the two matrix is: 
[[ 0  1  1  9]
 [ 0  3  3 27]
 [ 0  2  2 18]
 [ 0  6  6 54]]


Transformation using python


In [3]:
m=[[1,2],[3,4],[5,6]]
for row in m:
  print(row)
res=[[m[j][i] for j in range(len(m))] for i in range(len(m[0]))]
print("\n")
for row in res:
  print(row)

[1, 2]
[3, 4]
[5, 6]


[1, 3, 5]
[2, 4, 6]


SVD using python

In [4]:
from numpy import array
from scipy.linalg import svd
print("array is: ")
A=array([[1,2],[3,4],[5,6]])
print(A)
u,s,vt=svd(A)
print("u")
print(u)
print("s")
print(s)
print("vt")
print(vt)

array is: 
[[1 2]
 [3 4]
 [5 6]]
u
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
s
[9.52551809 0.51430058]
vt
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
